FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt pika==1.3.2

COPY . .

USER 1000

CMD ["python", "worker/consumer.py"]
