FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt pika==1.3.2

COPY . .

EXPOSE 8080
USER 1000

CMD ["python", "-c", "from src import create_app; app = create_app(); app.run(host='0.0.0.0', port=8080)"]
